name = "remix-cloudflare-workers"

workers_dev = true
main = "./server.ts"
# https://developers.cloudflare.com/workers/platform/compatibility-dates
compatibility_date = "2023-04-20"

[site]
bucket = "./public"

[define]
"process.env.NODE_ENV" = "'production'"

[env.local.define]
"process.env.NODE_ENV" = "'development'"
"process.env.REMIX_DEV_SERVER_WS_PORT" = "8002"
